-- File auto generated by purescript-bridge! --
module Types where

import Data.Newtype (class Newtype)
import Prim (Array, Int, String)

import Data.Generic (class Generic)

newtype User =
    User {
      sId :: Int
    , sNames :: Array String
    }

derive instance genericUser :: Generic User

derive instance newtypeUser :: Newtype User _

